// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPI1bIpeMwnRjafOJFN69BaBznDVOJmA',
    appId: '1:650291928628:web:ac2a73e01e7558fe1a3461',
    messagingSenderId: '650291928628',
    projectId: 'canluaflutter',
    authDomain: 'canluaflutter.firebaseapp.com',
    storageBucket: 'canluaflutter.firebasestorage.app',
    measurementId: 'G-5JL9GVEKZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAun44sVuxI_OCpdTA1J43MoJfFSccWjV4',
    appId: '1:650291928628:android:1e5cf7d935a7e1f31a3461',
    messagingSenderId: '650291928628',
    projectId: 'canluaflutter',
    storageBucket: 'canluaflutter.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQcr42342cDfqodofaBvSGh3SdklN_I8w',
    appId: '1:650291928628:ios:68add610e080a9d61a3461',
    messagingSenderId: '650291928628',
    projectId: 'canluaflutter',
    storageBucket: 'canluaflutter.firebasestorage.app',
    iosBundleId: 'com.thinh.canlua',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQcr42342cDfqodofaBvSGh3SdklN_I8w',
    appId: '1:650291928628:ios:68add610e080a9d61a3461',
    messagingSenderId: '650291928628',
    projectId: 'canluaflutter',
    storageBucket: 'canluaflutter.firebasestorage.app',
    iosBundleId: 'com.thinh.canlua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmPI1bIpeMwnRjafOJFN69BaBznDVOJmA',
    appId: '1:650291928628:web:6318423b6e02c0c61a3461',
    messagingSenderId: '650291928628',
    projectId: 'canluaflutter',
    authDomain: 'canluaflutter.firebaseapp.com',
    storageBucket: 'canluaflutter.firebasestorage.app',
    measurementId: 'G-C7P597357Z',
  );
}
